# Generated by Django 4.2.13 on 2024-06-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tip',
        ),
    ]
