# Generated by Django 4.2.13 on 2024-06-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='waiterprofile',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='waiterprofile',
            name='wallet',
        ),
    ]
