# Generated by Django 4.2.13 on 2024-06-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_clientprofile_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='payment_method_id',
            new_name='stripe_payment_method_id',
        ),
    ]
